/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutUsBar: typeof import('./components/bar/AboutUsBar.vue')['default']
    AppBar: typeof import('./components/bar/AppBar.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ContactUsBar: typeof import('./components/bar/ContactUsBar.vue')['default']
    ContactUsContent: typeof import('./components/contact_us/ContactUsContent.vue')['default']
    FeeBar: typeof import('./components/bar/FeeBar.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Home: typeof import('./components/Home.vue')['default']
    NewsBar: typeof import('./components/bar/NewsBar.vue')['default']
    ProductCenterBar: typeof import('./components/bar/ProductCenterBar.vue')['default']
    ProductList: typeof import('./components/product/ProductList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
